version: 2
registries:
  python-index-pypi-python-org-simple:
    type: python-index
    url: https://pypi.python.org/simple/
    username: "${{secrets.PYTHON_INDEX_PYPI_PYTHON_ORG_SIMPLE_USERNAME}}"
    password: "${{secrets.PYTHON_INDEX_PYPI_PYTHON_ORG_SIMPLE_PASSWORD}}"

updates:
- package-ecosystem: pip
  insecure-external-code-execution: allow
  directory: "/"
  schedule:
    interval: daily
    time: "16:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: prometheus-client
    versions:
    - 0.10.0
  registries:
  - python-index-pypi-python-org-simple
