name: Update Docker Hub Description
on: [ release ]
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4.0.2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: markusressel/barcode-server
